# Generated by Django 6.1 on 2026-08-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.CharField(max_length=500)),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
